"""correção campo api_key 2

Revision ID: 0ca818d45f9e
Revises: 1c065c449478
Create Date: 2022-02-23 21:59:10.844930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca818d45f9e'
down_revision = '1c065c449478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    # ### end Alembic commands ###
