"""correção campo api_key

Revision ID: 1c065c449478
Revises: 21dbfe01dad5
Create Date: 2022-02-23 21:56:09.387560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c065c449478'
down_revision = '21dbfe01dad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    # ### end Alembic commands ###
